[package]
name = "StuddyAppt"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
chrono = "0.4"
mysql = "25"
derive_more = { version = "1", features = ["full"] }
dotenvy = "0.15"