[package]
name = "watchman"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.8.1"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
#lapin = "2.5.0"
#futures-lite = "2.5.0"
#tracing = "0.1.41"
#tracing-subscriber = "0.3.0"
#async-global-executor = "^2.0"